### PR TITLE
Support for Node 10.x & forces ASCII for socket writes

### LINKED ISSUE #22: node.js 10.x support?
In `package.json` it seems that node.js 10.x support is explicitly removed: `"node": ">=5.1 <10"`.

Is there a reason for this? The 10.x branch is a LTS branch and will be supported until 2021.

### PR DESCRIPTION
**Pull request by alecgorge**
Closes #22.

The tests still don't pass but it gives me an auth error with the `test` API key and when I use my own API key the test times out even though with `DEBUG=*` I can see everything worked fine.

### CODE REVIEW

**Comment by alecgorge** [comment]
The tests were originally timing out here because [`node-mitm` doesn't stub out `net.Socket.constructor`](https://github.com/moll/node-mitm/issues/42). 

The issue with the tests failing on v10.x are because of failures of `node-mitm` as well. [The stubbed out socket implementation returns `undefined` except for `v0.10.x` which returns `{}`](https://github.com/moll/node-mitm/blob/master/lib/internal_socket.js#L85-L89). Both are meant to indicate no error. In recent version of node.js (including 10.x), [there is an explicit check to make sure the underlying write functions (which `node-mitm` stubs out) only return `0` to indicate no error through a `err !== 0` check](https://github.com/nodejs/node/blob/master/lib/internal/stream_base_commons.js#L74).

I don't want to submit those patches to `node-mitm` because:
1. I've already sunk way more time than I wanted into this to add some simple metrics to my app
2. It already should work but the test is broken

Can we have this merged and a new release cut to support 10.x and when you have time go through to make all the tests work?

**Comment by janxious** [comment]
Probably can. One of us will look into this more tomorrow and probs cut a new release. Thanks for looking into it!

**Comment by alecgorge** [comment]
Thanks so much!

**Comment by janxious** [comment]
@alecgorge I continue to be a node novice, so do you have an opinion on  the best thing to do with changes to `package-lock.json` in dependencies? commit whatever npm spits out?

I have a changeset that fixes the tests, and your links helped me figure out how to do it.

**Comment by alecgorge** [comment]
@janxious yup, always commit whatever npm spits it

**Comment by janxious** [comment]
Cool.

Also, there is a new version 2.3.0 out for ya.

**Comment by moll** [comment]
Just FYI I've fixed Mitm.js for Node v10. It's waiting on confirmation (tracked in https://github.com/moll/node-mitm/issues/48) and should be out as patch-level release soon.

**Pull request merged**
